//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE_
    {
        public string ID { get; set; }
        public string USERNAME_ { get; set; }
        public string MESSAGE_DATA { get; set; }
        public string TYPE_ { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
    }
}
