//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_DETAIL
    {
        public string DETAIL_ID { get; set; }
        public string RECEIPT_ID { get; set; }
        public string PRODUCT_ { get; set; }
        public short AMOUNT_ { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual RECEIPT RECEIPT { get; set; }
    }
}
