//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CARTs = new HashSet<CART>();
            this.RECEIPTs = new HashSet<RECEIPT>();
        }
    
        public string USERNAME_ { get; set; }
        public string PASSWORD_ { get; set; }
        public string FULLNAME_ { get; set; }
        public string ADDRESS_ { get; set; }
        public string SEX_ { get; set; }
        public string PHONE_ { get; set; }
        public string AVATAR_ { get; set; }
        public string EMAIL_ { get; set; }
        public string TYPE_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART> CARTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT> RECEIPTs { get; set; }
    }
}
